### ISSUE TITLE
download provided weight

### ISSUE THREAD

**Issue by quang-ngh** [multimediaFor/EITLNet#1]
Sorry but I cannot download the provided weights either through Drive or Baidu. Can you double check the links

**Comment by zijieloooooou** [comment]
I can download from this [link](https://drive.google.com/file/d/1fr0PLfTs0l4aPERFUizAdXKPW1cOg05H/view?usp=drive_link) , you can try again.

**Comment by quang-ngh** [comment]
thanks alot!
