### ISSUE TITLE
Potential error in BAM class

### ISSUE THREAD

**Issue by 4lexir4** [multimediaFor/EITLNet#2]
At line `46` in `bam.py` you multiply `self.channel_att(in_tensor)` and `self.spatial_att(in_tensor)` whereas the paper suggests that they should be added. Am I missing something or is this an error? If so, do you expect significant impact on the performance?

**Comment by multimediaFor** [comment]
Yes, you are right. Our paper does have a few minor issues with the details, and everything should refer to our code. Thanks!
