### ISSUE TITLE
About the test result

### ISSUE THREAD

**Issue by flymao627** [multimediaFor/EITLNet#3]
Hello author, may I ask if the test results of the six methods in Table 1 were obtained after training 60971 images in the training dataset?

**Comment by multimediaFor** [comment]
The results of the five methods in Table 1 (not including ours) on the test datasets are either cited from their respective papers or obtained by testing with the publicly available weight files provided by the authors. We did not retrain these methods on our training dataset. Thanks!

**Comment by flymao627** [comment]
I saw that you said that the mask of the training dataset is 01 mask graph, and the black and white area can not be seen visually. Is this necessary for the mask graph of the test dataset ?

**Comment by multimediaFor** [comment]
We converted the masks in the training dataset to binary values (0 and 1) for the training process only. During testing, we used standard test datasets, which includes tampered images and binary masks (0 and 255). Thanks!
