### ISSUE TITLE
What data is used for mean and std?

### ISSUE THREAD

**Issue by 4lexir4** [multimediaFor/EITLNet#4]
Hi there

I’ve noticed that in `utils.py` in `preprocess_input` specific values are used for mean and standard deviation. What data was used to calculate these? I’ve tried getting these values using the data in `JPEGImages` but couldn’t get the same values. 

Thank you in advance for your time and attention.

**Comment by multimediaFor** [comment]
The means and standard deviations we use are from the ImageNet dataset, which are consistent with the dataset distribution used by the pre-trained model (MiT-b2).

**Comment by multimediaFor** [comment]
The means and standard deviations we use are from the ImageNet dataset, which are consistent with the dataset distribution used by the pretrained model (MiT-b2).
