### ISSUE TITLE
Google drive link doesn't work

### ISSUE THREAD

**Issue by discordinated** [multimediaFor/EITLNet#7]
The link to download the pretrained weights from Google drive just shows my google drive, it's not a link to the actual weights. Can you fix this and link to the actual weights on Google drive?

**Comment by multimediaFor** [comment]
really?
![image](https://github.com/user-attachments/assets/62e2c26c-0201-4d43-bc45-13e85555bc7f)

**Comment by multimediaFor** [comment]
> The link to download the pretrained weights from Google drive just shows my google drive, it's not a link to the actual weights. Can you fix this and link to the actual weights on Google drive?

May be you need to "science surf" on the internet.

**Comment by discordinated** [comment]
The link provided is incorrect.   No need to be rude

https://drive.google.com/drive/my-drive?hl=zh-cn  is a link to your own google drive, it is not to a link to a shared folder or shared file. You can tell that if you just look at the URL you have shared. It’s very obviously not a share link.  

No one else can open your personal drive by clicking that link. You have to select a folder or file and share that specifically. You have just copy pasted the url while signed in to google drive.

**Comment by zijieloooooou** [comment]
> The link provided is incorrect. No need to be rude
> 
> https://drive.google.com/drive/my-drive?hl=zh-cn is a link to your own google drive, it is not to a link to a shared folder or shared file. You can tell that if you just look at the URL you have shared. It’s very obviously not a share link.
> 
> No one else can open your personal drive by clicking that link. You have to select a folder or file and share that specifically. You have just copy pasted the url while signed in to google drive.

you can try this [link](https://drive.google.com/file/d/1fr0PLfTs0l4aPERFUizAdXKPW1cOg05H/view?usp=drive_link)

**Comment by multimediaFor** [comment]
Oh, thank you very much! I sincerely appreciate you pointing out this issue. I apologize for my oversight! You are absolutely right, and I will correct this mistake immediately. Once again, I want to express my gratitude to you!


> The link provided is incorrect. No need to be rude
> 
> https://drive.google.com/drive/my-drive?hl=zh-cn is a link to your own google drive, it is not to a link to a shared folder or shared file. You can tell that if you just look at the URL you have shared. It’s very obviously not a share link.
> 
> No one else can open your personal drive by clicking that link. You have to select a folder or file and share that specifically. You have just copy pasted the url while signed in to google drive.
